export default {
  login: 'MathisHumbert',
  id: 84037244,
  node_id: 'MDQ6VXNlcjg0MDM3MjQ0',
  avatar_url: 'https://avatars.githubusercontent.com/u/84037244?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/MathisHumbert',
  html_url: 'https://github.com/MathisHumbert',
  followers_url: 'https://api.github.com/users/MathisHumbert/followers',
  following_url:
    'https://api.github.com/users/MathisHumbert/following{/other_user}',
  gists_url: 'https://api.github.com/users/MathisHumbert/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/MathisHumbert/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/MathisHumbert/subscriptions',
  organizations_url: 'https://api.github.com/users/MathisHumbert/orgs',
  repos_url: 'https://api.github.com/users/MathisHumbert/repos',
  events_url: 'https://api.github.com/users/MathisHumbert/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/MathisHumbert/received_events',
  type: 'User',
  site_admin: false,
  name: 'Mathis Humbert ',
  company: null,
  blog: '',
  location: 'Mâcon, France',
  email: null,
  hireable: null,
  bio: 'French winemaker trying to learn coding Learning Front End Development Currently working on JavaScript',
  twitter_username: 'Mathis1Humbert',
  public_repos: 58,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2021-05-11T17:17:13Z',
  updated_at: '2021-10-29T13:25:43Z',
};
